# Generated by Django 4.0.2 on 2022-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_form', '0002_rename_price_books_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
